### ISSUE TITLE
Document configuration file?

### ISSUE THREAD

**Issue by ckuethe** [wmanth/git-repo-browser#34]
First, git-repo-browser doesn't create an example configuration if there isn't one. That causes a rather inscrutable json error on startup.

Second, it took more than a bit of trial and error and reading the source to get a working config for local repos

```
repo_one:
  config:
    local: mystuff/repo1/.git
  name: 'My Project 1'
  type: local
repo_two:
  config:
    local: acme/widget/.git
  name: 'ACME Widgets'
  type: local
other_repo:
  config:
    local: foocorp/secret/.git
  name: 'FooCorp Secret Project'
  type: local
```
